Items:
  note:
    material: PAPER
    name: "&p&l%currency% &s&lNote &7[Right Click]"
    lore:
      - "&f&oRight Click &7to redeem this %currency% note!"
      - " "
      - "&sValue&p %value% %currency%"
      - "&sSigner&p %signer%"
    enchanted: true
    SERVER-SIGNER: "Server"

  pouch:
    material: ENDER_CHEST
    name: "&p&l%currency% &s&lPouch &7[Right Click]"
    lore:
      - "&7Right click to receive %currency% with the"
      - "&7minimum of %min% and a maximum %max%"
      - " "
      - "&s&m=================================="
      - "&p&lMINIMUM &7%min%"
      - "&p&lMAXIMUM &7%max%"
      - "&s&m=================================="

Currencies:
  GEMS:
    primary: "<SOLID:b47cff>"
    secondary: "<SOLID:dc4dff>"
    join-amount: 10
    symbol: "◆"
  ###############################
  MONEY:
    primary: "<SOLID:9cff57>"
    secondary: "<SOLID:64dd17>"
    join-amount: 500
    symbol: "$"
  ###############################
  ORBS:
    primary: "<SOLID:ff7539>"
    secondary: "<SOLID:ff3d00>"
    join-amount: 5
    symbol: "☀"
  ###############################
